### ISSUE TITLE
Page doesn't work with SSL enabled, for any browser I've tried.

### ISSUE THREAD

**Issue by KhelbenArunsun** [dave-kennedy/por-code-wheel#1]
Believe me when I say, I'm stumped. I'm looking at the code (cloned to my machine) and have no idea what's wrong.

This is strange. Not bad, as I was going to keep a local copy anyway, but strange. Maybe a script needs to be reworked? Web browsers tend to block insecure scripts in SSL protected pages these days.

**Browsers I've tried:**
- Chromium
- Firefox
- Pale Moon
- Midori (Don't ask me why I thought it would work here. I was being thorough.)
- IceCat
- Otter-Browser

**OSes I tested:**
- Arch Linux
- Ubuntu
- Debian
- Fedora

I think it's probably github.io, not your code.

**Comment by dave-kennedy** [comment]
Sorry it took me so long to notice this! I fixed my notification settings.

I believe I know what the issue is and will fix it ASAP.
